= Template README

Within each template file are several features to guide the creation of the iTC documentation. These can be divided into three areas.

== iTC variables
In many of the templates there will be a series of lines after the header all starting with :iTC.

  :iTC-longname: Coffee Maker
  :iTC-shortname: CM-iTC
  :iTC-email: cm-itc-mailing-list@gmail.com
  :iTC-website: https://coffeemaker.github.io/
  :iTC-GitHub: https://github.com/coffeemaker/repository/

There may be more or less lines depending on the template, but all will follow this basic structure.

The purpose of these lines is to make it easier to enter this information within the template without needing to edit it individually every time. This can be done by entering the name between the colons inside curly brackets {}. When this is done, the value entered in the line above will be replaced when the file is processed.

For example, entering {iTC-website} would replace that with the URL specified in the line in the heading.

Using these variables will allow you to maintain consistency throughout the document.

The variable values that are currently being used can be found at this link:

https://github.com/itc-wgtools/cPP-Tools/wiki/Dummy-iTC-for-Examples

== Examples
The templates may provide some examples within the templates, but generally the templates have been kept "clean" to minimize what the iTC needs to edit out. Most of the text in a template needs to be there to meet the requirements of the Common Criteria specifications, but may need modifications based on the product type.

Examples are being shown here: https://itc-wgtools.github.io/examples/examples.html.

== Admonitions
Within Asciidoctor admonitions are blocks of text that when processed will stand out with an icon on the left of the text. Additionally, within the guide (so while you are editing it), these will also stand out due to how they are written.

Asciidoctor provides several admonitions that can be used within a document normally (such as NOTE or IMPORTANT). In addition to these, the Tools WG has created several specifically to provide guidance within the templates. These are not intended for final publication, but are provided to help editors in figuring out the documents.

An example admonition block would look like this:

  [BOILERPLATE]
  ====
  The following paragraphs need to be in the document and should be left alone.
  ====

In a published version of the document, this would have a lock show up on the left side of the text.

The following Tools WG admonitions have been created. All of these should be removed before final publication.

[cols=".^1,.^3",options="header"]
|===
|Admonition
|Description

|BOILERPLATE
|Text referenced here should be left alone as it is "standard"

|REVIEW
|While the text here is standard, it may need some modifications for the product type

|GUIDANCE
|Used to mark text for guiding what should be done in a section, that there are examples, etc

|===

For more questions about admonitions, including creating new ones, go to the https://github.com/itc-wgtools/itc_gentools[itc_gentools repository].